### ISSUE TITLE
--docker-context-dir failed dockerfile dependency scan

### ISSUE THREAD

**Issue by northtyphoon** [Azure/acr-builder#107]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened?**:
./acr-builder --git-url https://github.com/dotnet/dotnet-docker --git-branch master --docker-context-dir 2.0/runtime/jessie/amd64 --docker-file Dockerfile --working-dir ~/download

INFO[0000] Running command git clone -b master https://github.com/dotnet/dotnet-docker /home/bindu/download
Cloning into '/home/bindu/download'...
remote: Counting objects: 3689, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 3689 (delta 9), reused 15 (delta 9), pack-reused 3672
Receiving objects: 100% (3689/3689), 1.07 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1495/1495), done.
Checking connectivity... done.
INFO[0000] Running command git rev-parse --verify HEAD
5f63fbcc47a645d870687a4e9181a34eb131d3e2
ERRO[0000] Error opening dockerfile Dockerfile, error: open Dockerfile: no such file or directory

**The following command without using --docker-context-dir worked**
./acr-builder --git-url https://github.com/dotnet/dotnet-docker --git-branch master --docker-file 2.0/runtime/jessie/amd64/Dockerfile --working-dir ~/download

@NatalieGong  @shhsu  @ehotinger

**Comment by ehotinger** [comment]
@northtyphoon Can you elaborate on the full scenario right now? Just running the builder independently or is the scheduler/runner passing in bad combos? I asked Peter as part of #98 to simplify all the parameters. This will take some time. They all sort of work if you pass in the right things, but it's tricky right now.

**Comment by NatalieGong** [comment]
I ran into the same problem today. When I deployed the resource provider and scheduler onto to eastus dogfood and tried the command
az acr build -c https://github.com/NatalieGong/dotnet-docker.git#master:/2.0/runtime/stretch/amd64/Dockerfile -r yugongeast
it errors like this 
Sending build context to ACR Build as Id: yan
[2018-04-21T00:59:10Z] Attaching to the image cache...
time="2018-04-21T00:59:34Z" level=info msg="Running command docker login -u 00000000-0000-0000-0000-000000000000 --password-stdin yugongeast.azurecr-test.io"
Login Succeeded
time="2018-04-21T00:59:40Z" level=info msg="Running command git clone -b master https://github.com/NatalieGong/dotnet-docker.git /root/acr-builder/src"
Cloning into '/root/acr-builder/src'...
time="2018-04-21T00:59:40Z" level=info msg="Running command git rev-parse --verify HEAD"
998e67b1c89f4bf2e9cfa4544b67a68e7242d5c1
time="2018-04-21T00:59:40Z" level=error msg="Error opening dockerfile Dockerfile, error: open Dockerfile: no such file or directory"
Build ID: yan failed because of an internal error after 31.120698468s

However, if I build a context where the dockerfile is at the root directory of the git repository, the build succeeds. Obviously, the context flag for acr-builder is not what we expect it to be.

**Comment by ehotinger** [comment]
Context flags aren't a thing in Docker when you use `git clone` or `tar`. It's always assumed to be the root of the clone -or- the extraction. I decided a while ago that we shouldn't this, anything that works with passing in working directories or contexts beyond the docker file path is a hack.

**Comment by ehotinger** [comment]
yeah, need to standardize the contexts. Can use docker file path instead as a workaround until that work is done.

**Comment by NatalieGong** [comment]
Oh I am sorry for the wording here. I did not have the context flag for the command on the CLI. Rather, the branch and context are all packed inside the url, described as:
"Git URLs accept context configuration in their fragment section, separated by a colon :. The first part represents the reference that Git will check out, and can be either a branch, a tag, or a remote reference. The second part represents a subdirectory inside the repository that will be used as a build context."
Yes, there is no context flag but we still need to consider the situation when the Dockerfile is not located at the root directory of the git repo.

**Comment by ehotinger** [comment]
@NatalieGong ya I didn't see your `#` in the original post, that's why I deleted my comment sneakily. That should work.

**Comment by NatalieGong** [comment]
And the problem here is that the subdirectory is not dealt with properly on either the acr-builder side or the RP/Scheduler. It needs more investigation.

**Comment by NatalieGong** [comment]
😃

**Comment by northtyphoon** [comment]
From README: --docker-context-dir Docker build context. Optional, to be used alongside --dockerfile.

I see the code just passes dockerfile to depdencyscan function. Probably docker-context-dir never worked.

**Comment by northtyphoon** [comment]
After reading the code history, I think the documentation about `--docker-context-dir` and `--docker-file` arguments is not accurate. Based on the implementation, acr-build always expects `--docker-file` is either a full path or a path relative to the current working folder (which is the git source root). `--docker-context-dir` just scopes the files sent to the daemon which is also relative to the working folder.

So we need to update the documentation to clarify it. At the same time, @NatalieGong, you can update RP to update --docker-file to add the context folder path. Also make sure `--docker-context-dir` and `--docker-file` are all relative path (remove heading "/").
