### ISSUE TITLE
Untar fails if there's a .git folder included

### ISSUE THREAD

**Issue by ehotinger** [Azure/acr-builder#233]
Untar seems to fail during `build` if a `.git` folder is included.

See https://github.com/Azure/acr/issues/122

**Comment by northtyphoon** [comment]
@ehotinger I looked at the issue and noticed the it is not specific to .git folder. It's related to how files in .git folder are archived. As https://github.com/Azure/acr/issues/122, the files under `.git` folder are accidentally included in the tar but not .git folder, the unpack process will automatically create `.git` folder however the docker archive lib we use will also try to  change the owner of the new created `.git` folder to root. It will throw permission deny error.

Since users can configure .dockerignore file to exclude parent folder but explicitly include a few child folders or files, they will hit the same issue.

I send a tentative workaround. BTW: I checked the `docker build` could handle such tar file properly. But I'm not sure if they handle it differently.
