### ISSUE TITLE
Validate step properties

### ISSUE THREAD

**Issue by Jinhuafei** [Azure/acr-builder#264]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened?**:
Step id is used as running container name, if it contains a special character(e.g. a space), it will break the docker command. And this is hard to understand the root cause of the issue based on the error msg. This should be the case for other  parameters as well.

**Comment by ehotinger** [comment]
The same can be said of every property in `Step`. It's worth discussing how much value we add by re-writing all of Docker's validation.

**Comment by sajayantony** [comment]
@Jinhuafei can you paste the yaml file that caused this since I want to make sure that we can think about the scenario before fixing anything. 

1. If we throw an an error is it actionable by the person who create the yaml? 
2. Can we guide the developer to fix it by themselves?

I don't know if an extended name validation is needed since these are new files that is being authored but the first name check for container names seems very simple - 
https://github.com/moby/moby/blob/master/daemon/names/names.go#L9
But gets ugly along the createContainer Path.

**Comment by Jinhuafei** [comment]
here is a sample.

steps:
  - id: run helloworld
    cmd: hello-world

The error you will get is something like 'can not pull image helloworld'. ACB generates the cmd as "docker run --name run helloworld .......", so docker cli thinks helloworld is the image name.

I think if the property is only for ACB(e.g. ID), we should have some validation. If it's a property that docker cli understands(e.g. PORT), we can leave it to docker cli for validation(we can have assumption that the author knows what are valid value for docker cli)

**Comment by sajayantony** [comment]
Is there anything in the error that indicates that its a name issue. I'm trying to find out how can the developer unblock themselves.

**Comment by ehotinger** [comment]
@Jinhuafei Just FYI, ID is being used as a parameter to Docker CLI (`--name`). A start might be not allowing spaces in any of the commands, but it's all sorta meh at this point because we introduced shell-style vargs parsing. IE: you could put the entire run command in "ID" at this point, the other properties are just fluff helpers to add in the correct flag automatically.

**Comment by Jinhuafei** [comment]
Yeah, I'm aware of that. It's hard to know that ID is mapped to --name without knowing how acb works. My point is that we should do some basic validation on those properties that are implicitly mapped to docker cli arguments or not mapped to any. 

@sajayantony if the dev doesn't know the implementation details about acb, he/she could hardly figure out the root cause.

**Comment by sajayantony** [comment]
Ok we need to address this since Id is one of the top level properties that users will use so either we give a proper error message during execution to make the user understand this . 

```
 125 ❯ docker run --rm -it --name "TEST TEST" hello-world
docker: Error response from daemon: Invalid container name (TEST TEST), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
```

**Comment by ehotinger** [comment]
Closing this for now since we have #311. I think most of the other properties will be caught by CLI but since we're using Shell-style parsing lots of things can happen. Better to have specific examples over time which we can do validation for.
